### ISSUE TITLE
pin_up has a hard-coded dependency on a vulnerable version of httparty

### ISSUE THREAD

**Issue by joffotron** [dNitza/pin_up#23]
Hi,
We've got a dependabot warning about an issue affecting httparty, but we cannot upgrade cleanly as pin_up is locked to version 0.17.0 of that gem

![image](https://github.com/dNitza/pin_up/assets/336405/dc300b15-950f-4b56-b40d-944a14ccc125)

Security advisory for httparty: https://github.com/advisories/GHSA-5pq7-52mg-hr42

It would be great if pin_up could support the current version (and perhaps be a little more permissive in the version(s) it requires)

Thanks :)

**Comment by eugenmamaev** [comment]
Hi, @joffotron.
You can use this PR. [https://github.com/dNitza/pin_up/pull/24](https://github.com/dNitza/pin_up/pull/24)
It's compatible with the current httparty version.

**Comment by AMHOL** [comment]
[v1.4.4](https://rubygems.org/gems/pin_up/versions/1.4.4) has been released which removes the version lock on httparty.
