### ISSUE TITLE
Adding Subscriptions, Plans & Events API functionality

### ISSUE THREAD

**Issue by drej2k** [dNitza/pin_up#9]
Hi, 
I have been using pin_up on and off for the last year and am loving it. Great job!
Pin payments have released 3 beta APIs, Subscriptions, Plans & Events.
I am building a payment gateway using these 3 new APIs and would like to extend pin_up to wrap these APIs.
How does this sound?

**Comment by dNitza** [comment]
Hey @drej2k,

Sorry, I missed this!

Great to hear that this gem is useful to you :) And yeah if you want to go ahead and extend pin_up to wrap these APIs, that'd be great! What is the name of the name of the payment gateway you're building (and is it OSS).

Cheers,
Dan.

**Comment by drej2k** [comment]
Hi @dNitza,
Not an issue.
I am building a payment gateway for an app I am working on. The app will be open sourced in a couple of months!

Brilliant, I would rather extend this gem than create another!

So I am planning on submitting 4 PRs. 
1. Decouple all the current tests from a user's API test data
2. Plan API & tests
3. Subscription API & tests
4. Events API & tests

**Comment by drej2k** [comment]
Hi Dan,
Brilliant! I submitted the first PR last night. However, I realised I left 1 test commented out. So I will fix and resubmit the decouple-tests-from-api-branch
Regards,
Andre

**Comment by drej2k** [comment]
Ok PR updated(Decouple test from user API data & update readme). 
All test have been fixed :)
Review away!

**Comment by dNitza** [comment]
Thanks @drej2k! I will have a look over it tonight :)

**Comment by drej2k** [comment]
Hi Dan,

In case you have not seen a notification I have made a PR with the Plan API.

I have also finished the Subscription API but I want to wait to make that PR as it forks off from the Plan API branch.

Thanks

Andre

**Comment by dNitza** [comment]
Ah thanks! Yep, I missed the notification. I will check these PRs out tonight!

**Comment by drej2k** [comment]
Just submitted a PR for subscriptions!

**Comment by dNitza** [comment]
Nice one! I will have a look

**Comment by drej2k** [comment]
Thanks for reviewing and helping to accept my pull requests.
I will close this issue as I will PR Events at a later stage.
